StatikA/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from ckeditor_uploader import urls as ckeditor_urls
from testing import urls as testing_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^testing/', include(testing_urls, namespace='testing')),
    url(r'^$', TemplateView.as_view(template_name="index.html"), name='home'),
]

testing/urls.py
from django.conf.urls import url, include

from testing import views


urlpatterns = [
    url('TESTING', views.test_python, name='test_python'),
    url('OUTPUT', views.test_test, name='test_test'),
    url('STUFF', views.TESTING, name='TEST')
]

testing/models.py
from django.db import models



class Testing(models.Model):
    title = models.CharField(max_length=255)
    test_description = models.TextField(blank=True, default='')

    def __str__(self):
        return '{}: {}'.format(self.title, self.test_description)

    def get_absolute_url(self):
        return print("Hello")

testing/views.py
#!/bin/sh
import os
import subprocess
import tempfile
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, Context
from django.shortcuts import get_object_or_404, render, redirect
from testing.models import Testing
from django import forms
from codemirror2.widgets import CodeMirrorEditor

def test_python(request):
    return render(request, 'testing/upload_python.html',)

def TESTING(request):
    return render(request, 'testing/test_python.html',)


def test_test(request):
    context = {}
    if request.method == 'POST':
        input_text = request.POST.get('mytextbox')
        if len(input_text) == 0:
            print('Please insert textbox with code')
            # Could send this error message to the test_python view
        else:
            fd, file_name = tempfile.mkstemp()
            with open(file_name, 'w') as input_file:
                input_file.write(input_text)
            args = [
                "flake8",
                file_name,
            ]
            process = subprocess.Popen(args, stdout=subprocess.PIPE)
            results = process.communicate()[0]
            os.remove(file_name)
            results = results.replace(bytes('{}:'.format(file_name), 'ascii'), b'')
            context['results'] = results
            return render(request, 'testing/output.html', context)
    return redirect('testing:test_python')

class TestFrom(forms.Form):
    css = forms.CharField(widget=CodeMirrorEditor(options={'mode': 'css'}))

templates/index.html
{% extends "layout.html" %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
          <h1><center>Welcome to StatikA!</center></h1>
        <p>Static program analysis is the analysis of computer software that is performed without actually executing programs. In most cases the analysis is performed on some version of the source code, and in the other cases, some form of the object code.</p>
        <center><p><a class="btn btn-primary btn-lg" href="/testing/TESTING" role="button">Test My Code</a></p></center>
      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <h2>Here are some examples:</h2>
      <div class="row">
        <div class="col-md-4">
          <h2>Python Testing</h2>
            <p>Test here your python code</p>
          <p><a class="btn btn-default" href="/testing/TESTING" role="button">So Let's go &raquo;</a></p>
        </div>
        <!--<div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </--div>
        <div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>-->
      </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Static Analyzer{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <<style>
        h1 {
            margin-top: 60px;
            margin-left: 20px;
        }

    </style>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{%  url 'home' %}">StatikA</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
            </div>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>
    {% block content %}{% endblock %}

    <div class="container">
         <hr>

      <footer>
        <p>&copy; 2017 StacikA.</p>
      </footer>
    </div> <!-- /container -->
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

testing/templates/test_python.html
{% extends "layout.html" %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
          <br><h2><center>bandit</center></h2></br>

      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <br class="form-group">
        <label for="comment">Enter your code here:</label>
        <textarea class="form-control" rows="30" id="comment"></textarea>
        <br><p><a class="btn btn-primary btn-lg" href="#" role="button">Run code &raquo;</a></p></br>
      </div>
    </div>
{% endblock %}

testing/templates/testing/output.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
          <br><h2><center>Flake8</center></h2></br>

      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <br class="form-group">
        <form method="POST" action="{% url 'testing:test_test' %}">
            {% csrf_token %}
        <label for="comment">Enter code:</label>
        <!--<textarea class="form-control" rows="30" id="comment" name="mytextbox1"></textarea>-->
        <textarea id="mytextbox" name="mytextbox"></textarea>
        <p>Select a theme: <select onchange="selectTheme()" id=select>
        <option selected>default</option>
        <option>3024-night</option>
        <option>cobalt</option>
        <option>icecoder</option>
        <option>monokai</option>
        <option>panda-syntax</option>
        <option>twilight</option>
        <option>yeti</option>
        <option>zenburn</option>
        </select>
        </p>
        <input type="submit" class="btn btn-primary btn-lg" role="button" value="Run code &raquo;" name="mybtn">
        </form>
    </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <br class="form-group">
        <h2 for="comment">Analysis:</h2>
          <br>
        {{ results }}
      </div>


<link rel=stylesheet href="{% static 'plugins/CodeMirror/doc/docs.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/lib/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/3024-night.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror//theme/cobalt.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/icecoder.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/monokai.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/panda-syntax.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/twilight.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/yeti.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/zenburn.css' %}">
<script src="{% static 'plugins/CodeMirror/lib/codemirror.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/mode/javascript/javascript.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/selection/active-line.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/edit/matchbrackets.js' %}"></script>
<style type="text/css">
      .CodeMirror {border: 1px solid black; font-size:13px}
    </style>

<script>
  var editor = CodeMirror.fromTextArea(document.getElementById("mytextbox"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true
  });
  var input = document.getElementById("select");
  function selectTheme() {
    var theme = input.options[input.selectedIndex].textContent;
    editor.setOption("theme", theme);
    location.hash = "#" + theme;
  }
  var choice = (location.hash && location.hash.slice(1)) ||
               (document.location.search &&
                decodeURIComponent(document.location.search.slice(1)));
  if (choice) {
    input.value = choice;
    editor.setOption("theme", choice);
  }
  CodeMirror.on(window, "hashchange", function() {
    var theme = location.hash.slice(1);
    if (theme) { input.value = theme; selectTheme(); }
  });
</script>

{% endblock %}

testing/templates/testing/test_python.html
<!doctype html>
{% extends "layout.html" %}
{% load staticfiles %}

<link rel="stylesheet" type = "text/css" href="{% static 'testing/plugins/codemirror/lib/codemirror.css' %}">


{% block content %}
    <body>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
          <br><h2><center>Flake8</center></h2></br>
      </div>
    </div>
    <div class="ace_content">
      <!-- Example row of columns -->
      <br class="form-group">
        <label for="comment">Enter your code here:</label>
        <!--<input type="text" value="8" name="mytextbox" size="1"/>
        <input type="submit" class="btn" value="Click" name="mybtn">-->
        <div><textarea class="form-control" rows="30" id="mytextbox1" name="mytextbox1"></textarea></div>
        <a class="btn btn-primary btn-lg" href="/testing/TESTING" role="button" value="Click" name="mybtn">Run code &raquo;</a>
      </div>
    </div>


    <br>



<meta charset="utf-8"/>
<link rel=stylesheet href="{% static 'plugins/CodeMirror/doc/docs.css' %}">

<link rel="stylesheet" href="{% static 'plugins/CodeMirror/lib/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/monokai.css' %}">
<script src="{% static 'plugins/CodeMirror/lib/codemirror.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/mode/javascript/javascript.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/selection/active-line.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/edit/matchbrackets.js' %}"></script>
<style type="text/css">
      .CodeMirror {border: 1px solid black; font-size:13px}
    </style>

<form><textarea id="mytextbox" name="mytextbox">
</textarea></form>

<p>Select a theme: <select onchange="selectTheme()" id=select>
    <option selected>default</option>
    <option>monokai</option>
</select>
</p>

<script>
  var editor = CodeMirror.fromTextArea(document.getElementById("mytextbox"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true
  });
  var input = document.getElementById("select");
  function selectTheme() {
    var theme = input.options[input.selectedIndex].textContent;
    editor.setOption("theme", theme);
    location.hash = "#" + theme;
  }
  var choice = (location.hash && location.hash.slice(1)) ||
               (document.location.search &&
                decodeURIComponent(document.location.search.slice(1)));
  if (choice) {
    input.value = choice;
    editor.setOption("theme", choice);
  }
  CodeMirror.on(window, "hashchange", function() {
    var theme = location.hash.slice(1);
    if (theme) { input.value = theme; selectTheme(); }
  });
</script>

</body>
{% endblock %}

testing/templates/testing/upload_python.html
{% extends "layout.html" %}

{% load static %}

{% block content %}
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
          <br><h2><center>Flake8</center></h2></br>

      </div>
    </div>
    <div class="container">
      <!-- Example row of columns -->
      <br class="form-group">
        <form method="POST" action="{% url 'testing:test_test' %}">
            {% csrf_token %}
        <label for="comment">Enter code:</label>
        <!--<textarea class="form-control" rows="30" id="comment" name="mytextbox1"></textarea>-->
        <textarea id="mytextbox" name="mytextbox"></textarea>
        <p>Select a theme: <select onchange="selectTheme()" id=select>
        <option selected>default</option>
        <option>3024-night</option>
        <option>cobalt</option>
        <option>icecoder</option>
        <option>monokai</option>
        <option>panda-syntax</option>
        <option>twilight</option>
        <option>yeti</option>
        <option>zenburn</option>
        </select>
        </p>
        <input type="submit" class="btn btn-primary btn-lg" role="button" value="Run code &raquo;" name="mybtn">
        </form>
    </div>
    </div>

<link rel=stylesheet href="{% static 'plugins/CodeMirror/doc/docs.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/lib/codemirror.css' %}">
<link rel=stylesheet href="{% static 'plugins/CodeMirror/doc/docs.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/lib/codemirror.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/3024-night.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror//theme/cobalt.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/icecoder.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/monokai.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/panda-syntax.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/twilight.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/yeti.css' %}">
<link rel="stylesheet" href="{% static 'plugins/CodeMirror/theme/zenburn.css' %}">
<script src="{% static 'plugins/CodeMirror/lib/codemirror.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/mode/javascript/javascript.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/selection/active-line.js' %}"></script>
<script src="{% static 'plugins/CodeMirror/addon/edit/matchbrackets.js' %}"></script>
<style type="text/css">
      .CodeMirror {border: 1px solid black; font-size:13px}
    </style>

<script>
  var editor = CodeMirror.fromTextArea(document.getElementById("mytextbox"), {
    lineNumbers: true,
    styleActiveLine: true,
    matchBrackets: true
  });
  var input = document.getElementById("select");
  function selectTheme() {
    var theme = input.options[input.selectedIndex].textContent;
    editor.setOption("theme", theme);
    location.hash = "#" + theme;
  }
  var choice = (location.hash && location.hash.slice(1)) ||
               (document.location.search &&
                decodeURIComponent(document.location.search.slice(1)));
  if (choice) {
    input.value = choice;
    editor.setOption("theme", choice);
  }
  CodeMirror.on(window, "hashchange", function() {
    var theme = location.hash.slice(1);
    if (theme) { input.value = theme; selectTheme(); }
  });
</script>

{% endblock %}